/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 14 14:08:38 GMT 2018
 */

package weiss.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import weiss.util.ArrayList;
import weiss.util.Collection;
import weiss.util.Collections;
import weiss.util.Comparator;
import weiss.util.TreeSet;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Collections_ESTest extends Collections_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TreeSet<String> treeSet0 = new TreeSet<String>();
      Collections.DefaultComparator<String> collections_DefaultComparator0 = new Collections.DefaultComparator<String>();
      treeSet0.add((String) null);
      String string0 = Collections.max((Collection<? extends String>) treeSet0, (Comparator<? super String>) collections_DefaultComparator0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Comparator<Object> comparator0 = Collections.reverseOrder();
      TreeSet<Comparable<Object>> treeSet0 = new TreeSet<Comparable<Object>>(comparator0);
      treeSet0.add((Comparable<Object>) null);
      Comparable<Object> comparable0 = Collections.max((Collection<? extends Comparable<Object>>) treeSet0);
      assertNull(comparable0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TreeSet<String> treeSet0 = new TreeSet<String>();
      treeSet0.add("r2%EtHT?O4vDX.~mND");
      String string0 = Collections.max((Collection<? extends String>) treeSet0);
      assertEquals("r2%EtHT?O4vDX.~mND", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Comparator<Object> comparator0 = Collections.reverseOrder();
      // Undeclared exception!
      try { 
        Collections.max((Collection<? extends Integer>) null, (Comparator<? super Integer>) comparator0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("weiss.util.Collections", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TreeSet<String> treeSet0 = new TreeSet<String>();
      ArrayList<Object> arrayList0 = new ArrayList<Object>(treeSet0);
      ArrayList<Object> arrayList1 = arrayList0.subList(2576, (-1));
      Comparator<Object> comparator0 = Collections.reverseOrder();
      // Undeclared exception!
      try { 
        Collections.max((Collection<?>) arrayList1, (Comparator<? super Object>) comparator0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("weiss.util.ArrayList$ArrayListIterator", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      Integer integer0 = new Integer((-1));
      arrayList0.add(integer0);
      Comparator<Object> comparator0 = Collections.reverseOrder();
      arrayList0.add("1");
      // Undeclared exception!
      try { 
        Collections.max((Collection<?>) arrayList0, (Comparator<? super Object>) comparator0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      Comparator<Object> comparator0 = Collections.reverseOrder();
      // Undeclared exception!
      try { 
        Collections.max((Collection<? extends Integer>) treeSet0, (Comparator<? super Integer>) comparator0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("weiss.util.Collections", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Comparator<Object> comparator0 = Collections.reverseOrder();
      TreeSet<String> treeSet0 = new TreeSet<String>(comparator0);
      treeSet0.add("\"t39swRD");
      treeSet0.add("");
      String string0 = Collections.max((Collection<? extends String>) treeSet0, (Comparator<? super String>) comparator0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TreeSet<Comparable<Object>> treeSet0 = new TreeSet<Comparable<Object>>();
      // Undeclared exception!
      try { 
        Collections.max((Collection<? extends Comparable<Object>>) treeSet0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("weiss.util.Collections", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Comparator<Object> comparator0 = Collections.reverseOrder();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      TreeSet<String> treeSet0 = new TreeSet<String>(arrayList0);
      treeSet0.add("dbwVQi&Z69!I\"\"Y#>");
      treeSet0.add("");
      Object object0 = Collections.max((Collection<?>) treeSet0, (Comparator<? super Object>) comparator0);
      assertEquals("", object0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try { 
        Collections.max((Collection<? extends Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("weiss.util.Collections", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Collections.DefaultComparator<Integer> collections_DefaultComparator0 = new Collections.DefaultComparator<Integer>();
      Integer integer0 = new Integer(26);
      int int0 = collections_DefaultComparator0.compare(integer0, integer0);
      assertEquals(0, int0);
  }
}
