/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 14 14:08:48 GMT 2018
 */

package weiss.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import weiss.util.EmptyStackException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EmptyStackException_ESTest extends EmptyStackException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EmptyStackException emptyStackException0 = new EmptyStackException("gq;");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EmptyStackException emptyStackException0 = new EmptyStackException();
  }
}
