/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 14 14:03:42 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.FileNotFoundException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OPTCacheSimulator_ESTest extends OPTCacheSimulator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      OPTCacheSimulator oPTCacheSimulator0 = new OPTCacheSimulator(0);
      int int0 = oPTCacheSimulator0.getCapacity();
      assertEquals(0, oPTCacheSimulator0.getNumHits());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      OPTCacheSimulator oPTCacheSimulator0 = new OPTCacheSimulator((-3605));
      int int0 = oPTCacheSimulator0.getCapacity();
      assertEquals((-3605), int0);
      assertEquals(0, oPTCacheSimulator0.getNumHits());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      OPTCacheSimulator oPTCacheSimulator0 = new OPTCacheSimulator(6);
      // Undeclared exception!
      try { 
        oPTCacheSimulator0.processSequence("inputs/input5_reverse.txt", "inputs/input5_reverse.txt");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("weiss.util.TreeSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      OPTCacheSimulator oPTCacheSimulator0 = new OPTCacheSimulator(0);
      // Undeclared exception!
      oPTCacheSimulator0.processSequence("inputs/input5_reverse.txt", "inputs/input5_reverse.txt");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      OPTCacheSimulator oPTCacheSimulator0 = new OPTCacheSimulator(112);
      // Undeclared exception!
      try { 
        oPTCacheSimulator0.processSequence("inputs/input1_distance.txt", "inputs/input1_distance.txt");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"inf\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      OPTCacheSimulator oPTCacheSimulator0 = new OPTCacheSimulator(0);
      // Undeclared exception!
      try { 
        oPTCacheSimulator0.processSequence((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      OPTCacheSimulator oPTCacheSimulator0 = new OPTCacheSimulator(1262);
      try { 
        oPTCacheSimulator0.processSequence("mr(USJuT!r", "mr(USJuT!r");
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // mr(USJuT!r (No such file or directory)
         //
         verifyException("java.io.FileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      OPTCacheSimulator oPTCacheSimulator0 = new OPTCacheSimulator(0);
      oPTCacheSimulator0.symbolTable = null;
      // Undeclared exception!
      try { 
        oPTCacheSimulator0.access((-3702), 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      OPTCacheSimulator oPTCacheSimulator0 = new OPTCacheSimulator(2112);
      // Undeclared exception!
      try { 
        oPTCacheSimulator0.processSequence("inputs/input5_reverse.txt", "inputs/input1_distance.txt");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      OPTCacheSimulator oPTCacheSimulator0 = new OPTCacheSimulator(1594);
      oPTCacheSimulator0.processSequence("inputs/input1.txt", "inputs/input1.txt");
      int int0 = oPTCacheSimulator0.getNumMisses();
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      OPTCacheSimulator oPTCacheSimulator0 = new OPTCacheSimulator(32);
      boolean boolean0 = oPTCacheSimulator0.access(32, 32);
      assertFalse(boolean0);
      assertEquals(0, oPTCacheSimulator0.getNumHits());
      assertEquals(32, oPTCacheSimulator0.getCapacity());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      OPTCacheSimulator oPTCacheSimulator0 = new OPTCacheSimulator((-2233));
      boolean boolean0 = oPTCacheSimulator0.access((-2233), (-2233));
      assertFalse(boolean0);
      
      boolean boolean1 = oPTCacheSimulator0.access((-2233), (-2233));
      assertEquals((-2233), oPTCacheSimulator0.getCapacity());
      assertTrue(boolean1);
      assertEquals(0, oPTCacheSimulator0.getNumMisses());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      OPTCacheSimulator oPTCacheSimulator0 = new OPTCacheSimulator(2112);
      int int0 = oPTCacheSimulator0.getNumHits();
      assertEquals(2112, oPTCacheSimulator0.getCapacity());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      OPTCacheSimulator oPTCacheSimulator0 = new OPTCacheSimulator(2112);
      int int0 = oPTCacheSimulator0.getNumMisses();
      assertEquals(2112, oPTCacheSimulator0.getCapacity());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      OPTCacheSimulator.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      OPTCacheSimulator oPTCacheSimulator0 = new OPTCacheSimulator(1594);
      int int0 = oPTCacheSimulator0.getCapacity();
      assertEquals(1594, int0);
      assertEquals(0, oPTCacheSimulator0.getNumHits());
  }
}
