/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 14 14:05:02 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SymbolRecord_ESTest extends SymbolRecord_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SymbolRecord symbolRecord0 = new SymbolRecord(1, 0);
      int int0 = symbolRecord0.getLastAccessTime();
      assertEquals(1, symbolRecord0.getAddress());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SymbolRecord symbolRecord0 = new SymbolRecord(0, 101);
      symbolRecord0.setLastAccessTime((-2160));
      int int0 = symbolRecord0.getLastAccessTime();
      assertEquals((-2160), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SymbolRecord symbolRecord0 = new SymbolRecord(0, 101);
      int int0 = symbolRecord0.getAddress();
      assertEquals(101, symbolRecord0.getLastAccessTime());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SymbolRecord symbolRecord0 = new SymbolRecord(1, 0);
      int int0 = symbolRecord0.getAddress();
      assertEquals(0, symbolRecord0.getLastAccessTime());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SymbolRecord symbolRecord0 = new SymbolRecord((-589), 447);
      int int0 = symbolRecord0.getAddress();
      assertEquals((-589), int0);
      assertEquals(447, symbolRecord0.getLastAccessTime());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SymbolRecord symbolRecord0 = new SymbolRecord((-589), 447);
      int int0 = symbolRecord0.getLastAccessTime();
      assertEquals(447, int0);
      assertEquals((-589), symbolRecord0.getAddress());
  }
}
